version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: golang_lottery_mysql
    #command: --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/config/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/data5.7/:/var/lib/mysql/:rw
      - ./logs/mysql/:/var/log/mysql/:rw
      - ./mysql/sql/:/root/sql/:rw
    networks:
      - back-tier
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"

  redis:
    # 指定镜像
    image: redis:5
    container_name: golang_lottery_redis
    ports:
      - 6379:6379
    volumes:
      # - "./redis/conf:/usr/local/etc/redis"
      - "./redis/data:/data"
    command:
      redis-server
    networks:
      - back-tier

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: golang_lottery_phpmyadmin
    ports:
      - "8088:80"
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"
      PMA_HOST: golang_lottery_mysql
    networks:
      - back-tier

networks:
  # front-tier:
  back-tier:
